### ISSUE TITLE
DOM exception

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ymeteor#19]
I am still getting this error.
```
I20191004-09:53:29.745(2)? error Error: Evaluation failed: DOMException: Failed to execute 'querySelector' on 'Document': '# ' is not a valid selector.
I20191004-09:53:29.746(2)?     at __puppeteer_evaluation_script__:1:33
I20191004-09:53:29.746(2)?     at ExecutionContext._evaluateInternal (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
I20191004-09:53:29.746(2)?     at <anonymous>
I20191004-09:53:29.746(2)?     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
I20191004-09:53:29.746(2)?   -- ASYNC --
I20191004-09:53:29.746(2)?     at ExecutionContext.<anonymous> (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/helper.js:111:15)
I20191004-09:53:29.747(2)?     at ElementHandle.$ (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/JSHandle.js:395:50)
I20191004-09:53:29.747(2)?     at ElementHandle.<anonymous> (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/helper.js:112:23)
I20191004-09:53:29.747(2)?     at DOMWorld.$ (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/DOMWorld.js:121:34)
I20191004-09:53:29.747(2)?     at <anonymous>
I20191004-09:53:29.747(2)?     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
I20191004-09:53:29.747(2)?   -- ASYNC --
I20191004-09:53:29.747(2)?     at Frame.<anonymous> (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/helper.js:111:15)
I20191004-09:53:29.747(2)?     at Page.$ (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/Page.js:318:29)
I20191004-09:53:29.747(2)?     at Page.<anonymous> (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/helper.js:112:23)
I20191004-09:53:29.748(2)?     at Promise.asyncApply (server/atc.js:153:54)
I20191004-09:53:29.748(2)?     at /home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20191004-09:53:29.748(2)?  => awaited here:
I20191004-09:53:29.748(2)?     at Function.Promise.await (/home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20191004-09:53:29.748(2)?     at Promise.asyncApply (server/atc.js:153:43)
I20191004-09:53:29.748(2)?     at /home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20191004-09:53:29.748(2)?  => awaited here:
I20191004-09:53:29.748(2)?     at Function.Promise.await (/home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20191004-09:53:29.748(2)?     at Promise.asyncApply (server/atc.js:292:21)
I20191004-09:53:29.749(2)?     at /home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by zdavatz** [comment]
The application is now looping with this error.

**Comment by zdavatz** [comment]
I am doing `meteor reset` and running the App again with `meteor --settings atc.json`
