### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ymeteor#32]
I am getting a timeout error:
`meteor --once --settings pharma.json`
```
I20200120-08:18:21.115(1)? error TimeoutError: waiting for selector "#clause > div > div > table:nth-child(2) > tbody > tr.dom_if\:\:\!getApplInfo\(\)\.isFZKNavigationDisabled\(\) > td:nth-child(2) > a.wbbluebutton.dom_action\:\:AcceptFZK.dom_translate\:\:amis\.clause\.accept" failed: timeout 30000ms exceeded
I20200120-08:18:21.116(1)?     at new WaitTask (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/DOMWorld.js:561:28)
I20200120-08:18:21.116(1)?     at DOMWorld._waitForSelectorOrXPath (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/DOMWorld.js:490:22)
I20200120-08:18:21.116(1)?     at DOMWorld.waitForSelector (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/DOMWorld.js:444:17)
I20200120-08:18:21.116(1)?     at Frame.waitForSelector (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/FrameManager.js:628:47)
I20200120-08:18:21.117(1)?     at Frame.<anonymous> (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/helper.js:112:23)
I20200120-08:18:21.117(1)?     at Page.waitForSelector (/home/zeno/.software/ymeteor/node_modules/puppeteer/lib/Page.js:1089:29)
I20200120-08:18:21.117(1)?     at server/flowPub.js:41:16
I20200120-08:18:21.118(1)?     at /home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20200120-08:18:21.118(1)?  => awaited here:
I20200120-08:18:21.118(1)?     at Function.Promise.await (/home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20200120-08:18:21.118(1)?     at server/flowPub.js:41:5
I20200120-08:18:21.119(1)?     at /home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20200120-08:18:21.119(1)?  => awaited here:
I20200120-08:18:21.119(1)?     at Function.Promise.await (/home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20200120-08:18:21.119(1)?     at server/pharma.js:293:5
I20200120-08:18:21.120(1)?     at /home/zeno/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 {
I20200120-08:18:21.120(1)?   name: 'TimeoutError'
I20200120-08:18:21.120(1)? }
```

**Comment by zdavatz** [comment]
this is related: #30
