### ISSUE TITLE
production server error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ymeteor#35]
running the command `https://github.com/zdavatz/ymeteor/issues/35` resulted in
```
=> App running at: http://localhost:3000/
W20200121-14:43:21.556(1)? (STDERR) (node:26710) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
W20200121-14:43:21.557(1)? (STDERR) /usr/local/src/ymeteor/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
W20200121-14:43:21.558(1)? (STDERR) 
W20200121-14:43:21.558(1)? (STDERR) 
W20200121-14:43:21.558(1)? (STDERR) TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
W20200121-14:43:21.559(1)? (STDERR) 
W20200121-14:43:21.559(1)? (STDERR)     at onClose (/usr/local/src/ymeteor/node_modules/puppeteer/lib/Launcher.js:349:14)
W20200121-14:43:21.560(1)? (STDERR)     at Interface.helper.addEventListener (/usr/local/src/ymeteor/node_modules/puppeteer/lib/Launcher.js:338:50)
W20200121-14:43:21.560(1)? (STDERR)     at emitNone (events.js:111:20)
W20200121-14:43:21.560(1)? (STDERR)     at Interface.emit (events.js:208:7)
W20200121-14:43:21.561(1)? (STDERR)     at Interface.close (readline.js:368:8)
W20200121-14:43:21.561(1)? (STDERR)     at Socket.onend (readline.js:147:10)
W20200121-14:43:21.562(1)? (STDERR)     at emitNone (events.js:111:20)
W20200121-14:43:21.562(1)? (STDERR)     at Socket.emit (events.js:208:7)
W20200121-14:43:21.562(1)? (STDERR)     at endReadableNT (_stream_readable.js:1064:12)
W20200121-14:43:21.563(1)? (STDERR)     at _combinedTickCallback (internal/process/next_tick.js:139:11)
W20200121-14:43:21.563(1)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
W20200121-14:43:21.563(1)? (STDERR)  => awaited here:
W20200121-14:43:21.564(1)? (STDERR)     at Function.Promise.await (/home/zdavatz/.meteor/packages/promise/.0.11.2.1jju96c.li1k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20200121-14:43:21.564(1)? (STDERR)     at Promise.asyncApply (server/swissmedic-o.js:183:18)
W20200121-14:43:21.564(1)? (STDERR)     at /home/zdavatz/.meteor/packages/promise/.0.11.2.1jju96c.li1k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20200121-14:43:21.565(1)? (STDERR)  => awaited here:
W20200121-14:43:21.565(1)? (STDERR)     at Function.Promise.await (/home/zdavatz/.meteor/packages/promise/.0.11.2.1jju96c.li1k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20200121-14:43:21.566(1)? (STDERR)     at Promise.asyncApply (server/swissmedic-o.js:172:9)
W20200121-14:43:21.566(1)? (STDERR)     at /home/zdavatz/.meteor/packages/promise/.0.11.2.1jju96c.li1k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20200121-14:43:21.566(1)? (STDERR) (node:26710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
W20200121-14:43:21.567(1)? (STDERR) (node:26710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zdavatz** [comment]
sudo apt-get install libx11-xcb1 libxcomposite18 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libnss3 libcups2 libxss1 libxrandr2 libasound2 libatk1.0-0 libpangocairo-1.0-0 libgtk-3-0

**Comment by zdavatz** [comment]
[see](https://medium.com/@cloverinks/how-to-fix-puppetteer-error-ibx11-xcb-so-1-on-ubuntu-152c336368)
